# Generated by Django 2.0.3 on 2018-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneTable', '0002_auto_20180527_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('number', models.IntegerField()),
                ('float', models.FloatField()),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),

    ]
