# Generated by Django 2.0.3 on 2018-05-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneTable', '0001_initial'),
    ]


